In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1195, 8734, 7921, 8873],
 [1195, 8734, 7921, 2057],
 [1195, 8652, 7921, 4993],
 [5565, 484, 32, 2816, 5990],
 [5565, 484, 32, 2816, 3830],
 [1691, 1195, 5275, 7921, 9243],
 [9087, 946, 1048, 2816]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1195 8734 7921 8873]
 [   0    0    0    0 1195 8734 7921 2057]
 [   0    0    0    0 1195 8652 7921 4993]
 [   0    0    0 5565  484   32 2816 5990]
 [   0    0    0 5565  484   32 2816 3830]
 [   0    0    0 1691 1195 5275 7921 9243]
 [   0    0    0    0 9087  946 1048 2816]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 278ms/step


array([[[ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
          4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
         -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
          2.61453129e-02],
        [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
          4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
         -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
          2.61453129e-02],
        [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
          4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
         -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
          2.61453129e-02],
        [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
          4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
         -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
          2.61453129e-02],
        [-9.54066589e-03,  6.74033165e-03, -2.54288800e-02,
          4.19471748e-02, -3.19008380e-02,  1.67820603e-03,
          1.99659206e-02,  4.33334224e-02, -2.132245

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 1195, 8734, 7921, 8873])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 63ms/step


array([[ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
         4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
        -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
         2.61453129e-02],
       [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
         4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
        -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
         2.61453129e-02],
       [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
         4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
        -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
         2.61453129e-02],
       [ 4.99031693e-03,  3.99487875e-02,  2.79632956e-03,
         4.20281999e-02,  3.00266594e-03, -4.66182344e-02,
        -4.31361198e-02, -1.80164687e-02,  8.19563866e-05,
         2.61453129e-02],
       [-9.54066589e-03,  6.74033165e-03, -2.54288800e-02,
         4.19471748e-02, -3.19008380e-02,  1.67820603e-03,
         1.99659206e-02,  4.33334224e-02, -2.13224534e-02,
         1.